/*
 *
 */

package pythagorasbaum;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.0
 *
 */

public class PythagorasFrame extends javax.swing.JFrame {

    private int winw, winh;                                                                                             // Window width, Window height
    private PythagorasBaum panel;

    public PythagorasFrame() {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        quit = new javax.swing.JMenuItem();

        quit.setText("Beenden");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(quit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(100, 100));
        setLocationByPlatform(true);
        setName("mainframe"); // NOI18N
        setUndecorated(true);
        setSize(new java.awt.Dimension(800, 500));
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        dispose();
    }//GEN-LAST:event_quitActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        switch ( evt.getButton() ) {
            case 3:
                // rechter Mausbutton
                jPopupMenu1.show( evt.getComponent(), evt.getX(), evt.getY() );
                break;
            case 2:
                // mittlerer Mausbutton
                setLocation( evt.getXOnScreen()-winw/2, evt.getYOnScreen()-winh/2 );
            case 1:
                // linker Mausbutton
                repaint();
                break;
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        winw += evt.getWheelRotation()*winw*0.1;                                                                        // 10% pro "Tick"
        winh += evt.getWheelRotation()*winh*0.1;                                                                        // 10% pro "Tick"
        super.setSize(winw, winh);
        panel.setSize(winw, winh);
    }//GEN-LAST:event_formMouseWheelMoved

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        int depth = panel.getDepth();
        double phi = panel.getPhi();
        switch ( evt.getKeyChar() ) {
            case '+':
            case 'w':
                ++depth;
                panel.setDepth(depth);
                break;
            case '-':
            case 's':
                --depth;
                panel.setDepth(depth);
                break;
            case 'a':
                panel.setPhi(phi-1.0);
                break;
            case 'd':
                panel.setPhi(phi+1.0);
                break;
        }
        repaint();
    }//GEN-LAST:event_formKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater( new Runnable() {
            @Override
            public void run() {
                new PythagorasFrame().setVisible(true);
            }
        });
    }

    private void initComponents2() {
        winw = super.getSize().width;
        winh = super.getSize().height;
        panel = new PythagorasBaum(winw, winh);
        getContentPane().add(panel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem quit;
    // End of variables declaration//GEN-END:variables

}
